[workspace]
resolver = "2"

members = [
  "cidr_calc",
  "cidr_lib",
]

[workspace.dependencies]
rstest = "0.18.2"
pretty_assertions = "1.4.0"
serde = { version = "1.0.193", features = ["derive"] }
serde_json = "1.0.108"
