name: Publish Crate(s)
on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Which crate to publish'
        required: true
        type: choice
        options:
        - cidr_lib
        - cidr_calc
jobs:
  publish-lib:
    uses: pitoniak32/actions/.github/workflows/rust-publish-crate.yml@main
    with:
      package-name: ${{ inputs.publish }}
    secrets: inherit
