name: Publish Crate
on:
  workflow_dispatch: {}
jobs:
  publish-crate:
    uses: pitoniak32/actions/.github/workflows/rust-publish-crate.yml@main
    with:
      package-name: cidr_calc
    secrets: inherit
